Home work
GeraskinDenis/Skypro_hw1 pull request #4
Opened 2022-01-31 18:20 UTC by GeraskinDenis

Домашняя работа 1.3

2022-01-31 22:48 UTC, OKrylov requested changes
В целом практически идеально выполненная работа. Условные операторы используются верно и применены должным образом в каждой задаче. Есть несколько небольших недочетов по коду, просьба обратить на них внимание

2022-01-31 22:48 UTC, OKrylov commented on src/ru/skypro/HomeWork_1_3.java
> +            boolean clientOS = false;
по заданию мы должны использовать числовой тип и значения 0 или 1. `clientOS = false` с первого взгляда говорит о том, что у клиента не будет никакой OS

2022-01-31 22:48 UTC, OKrylov commented on src/ru/skypro/HomeWork_1_3.java
> +            if ((year - leapYear) % 4 > 0) {
500 год невисокосный, но проходит по условиям. Лучше проверить явно на все условия (кратностьи 4 или 400, но не 100)

2022-01-31 22:48 UTC, OKrylov commented on src/ru/skypro/HomeWork_1_3.java
> +            if(distanceLeft > 0)
по сути задача не подразумевала поиска некой общей формулы, можно было задать все явно в 3 условных оператора на каждый интервал

2022-01-31 22:48 UTC, OKrylov commented on src/ru/skypro/HomeWork_1_3.java
> +            {
```suggestion
            switch (monthNumber) {
```
в Java принято расставлять открывающиеся скобки на той же строке, что и оператор/метол

2022-02-01 06:37 UTC, GeraskinDenis commented on src/ru/skypro/HomeWork_1_3.java
> +            boolean clientOS = false;
А я подумал, что задание составлено не верно. Объявить переменную, что бы в ней хранить 0 или 1, когда тема была про boolean, Исправил.

2022-02-01 07:08 UTC, GeraskinDenis commented on src/ru/skypro/HomeWork_1_3.java
> +            if ((year - leapYear) % 4 > 0) {
Исправил!

2022-02-01 07:12 UTC, GeraskinDenis commented on src/ru/skypro/HomeWork_1_3.java
> +            if(distanceLeft > 0)
В условии написано:
"То есть с каждым следующим интервалом доставки срок увеличивается на 1 день."
Вот я подумал вывести формулу. Исправил.

2022-02-01 07:17 UTC, GeraskinDenis commented on src/ru/skypro/HomeWork_1_3.java
> +            {
Исправил!

2022-02-01 23:12 UTC, OKrylov approved these changes
По исправлениям все отлично, замечаний по коду не имею

2022-02-03 21:21 UTC, merged